import requests
import threading
from datetime import datetime
from gps_logger import get_location

import os

BOT_TOKEN = os.getenv("BOT_TOKEN")
CHAT_ID = os.getenv("CHAT_ID")


def _send(message):

    url = (
        f"https://api.telegram.org/bot"
        f"{BOT_TOKEN}/sendMessage"
    )

    requests.post(
        url,
        data={
            "chat_id": CHAT_ID,
            "text": message
        },
        timeout=5
    )


def send_alert(reason, score, location):
    
    if location:

        lat = location["lat"]
        lng = location["lng"]

        maps_link = (
            f"https://maps.google.com/?q="
            f"{lat},{lng}"
        )

    else:

        lat = "Unknown"
        lng = "Unknown"
        maps_link = "Unavailable"

    if score >= 80:
        status = "ATTENTIVE"

    elif score >= 50:
        status = "FATIGUED"

    else:
        status = "CRITICAL"

    message = f"""
🚗 DRIVEGUARD AI ALERT

━━━━━━━━━━━━━━

⚠️ Event
{reason}

🧠 Driver Status
{status}

📊 Safety Score
{score}/100

📅 Time
{datetime.now().strftime('%d-%m-%Y %H:%M:%S')}

📍 Latitude
{lat}

📍 Longitude
{lng}

🗺️ Live Location
{maps_link}

━━━━━━━━━━━━━━

Generated by DriveGuard AI
Driver Monitoring System
"""

    threading.Thread(
        target=_send,
        args=(message,),
        daemon=True
    ).start()
